### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by bubnenkoff** [vouill/vue-slideout#1]
https://snag.gy/J720KT.jpg

All code is from sample.

**Comment by vouill** [comment]
What is your `vue` and `vue-slideout` version ?

**Comment by bubnenkoff** [comment]
"dependencies": {
    "vue": "^2.1.0",
    "vue-slideout": "^1.3.0"
  },

**Comment by bubnenkoff** [comment]
Here is my full package: https://ufile.io/426e0

**Comment by vouill** [comment]
Your issue isn't `vue-slideout` related.
In your `LeftSlider.vue` file you name this component `'Slideout'` the same as the `Slideout`component your are using inside. It creates an infinite loop (hence the error firing).

To solve your issue, in `LeftSlider.vue` replace : 

```javascript
name: 'Slideout'
```

by

```javascript
name: 'LeftSlider' // it can be anything else
```

Keep me updated :)

**Comment by bubnenkoff** [comment]
Oh, big thanks!
When I should specify name? Is `name` value = tag name? Like "name: foo"  create tag `<foo> </foo>` ? I tried examples and look like `name` is optional.

  import Slideout from 'vue-slideout' // ok I import Slideout 
  export default {
    name: 'LeftSlider', // should be same as above? In my case no
    components: {
      Slideout // it should be equal of first line? 
    },

**Comment by vouill** [comment]
[See](https://vuejs.org/v2/api/#name)

The name option either helps when debug by naming components in the tree, or help doing recursive stuff ( which you accidentally did ).
It's optionnal, you can even choose to not use it.

now about your code : 

```javascript
import Slideout from 'vue-slideout' // ok I import Slideout
export default {
name: 'LeftSlider', // should be same as above? In my case no
// No this should not be the same as above, this is the LeftSlider component, above is Slideout component,they are 2 different components, their names must be different or you ll have recursive calls. 
// This name field refers to this component, hence 'LeftSlider' or even if you want 'Left-Slider'
components: {
Slideout // it should be equal of first line?
// this refers to all the child components of this component, in this case LeftSlider component renders also a Slideout component, hence it's presence here
},
```
