### ISSUE TITLE
how to keep it open by default?

### ISSUE THREAD

**Issue by jj999** [vouill/vue-slideout#11]
Maybe it is trivial question, but what is the cleanest way to keep it open by default?

Thank you!

**Comment by vouill** [comment]
Hello !
I am sorry i haven't seen your notification in my github feed, hence the huge delay.

I do not think it has a clean way to keep it open by default beside the [CSS](https://github.com/Mango/slideout/issues/77) way. 

I would open an issue on the [slideout repo](https://github.com/Mango/slideout) if i were you.

Keep me updated !

Cheers.

**Comment by vouill** [comment]
Closing this issue since no updates
