### ISSUE TITLE
Event emitter should dispatch the relative data

### ISSUE THREAD

**Issue by rockylhc** [vouill/vue-slideout#12]
I've found out that in slideout.vue line 54
`this.$emit('on-' + event, event)`
isn't populating the data to the event listener, perhaps change those lines to
 `        this.slideout.on(event, (data) => {
          this.$emit('on-' + event, data)`
could fix the issue?

**Comment by vouill** [comment]
Thanks for opening the issue !
You are indeed right, i will push this fix :)

**Comment by vouill** [comment]
Updated, thanks for your issue !
