### ISSUE TITLE
.toggle() is not a function

### ISSUE THREAD

**Issue by juanpprieto** [vouill/vue-slideout#13]
Hey there,

Thanks for sharing the plugin! 

I am trying to access the .toggle() function you mention in the docs via the component instance, but the method doesn't seem to be available. Am I missing anything?

Here is a screenshot showing there error. Thanks.

<img width="553" alt="screen shot 2018-01-17 at 12 01 11" src="https://user-images.githubusercontent.com/12080141/35064283-5cbaa7d8-fb7e-11e7-8be1-941636ed38ca.png">

**Comment by vouill** [comment]
Hello !
You need to access the slideout data in the component you accessed:

try this:
`this.$ref.slideOut.slideout.toggle()`

Keep me updated :)
