### ISSUE TITLE
Error when using with nuxt.js

### ISSUE THREAD

**Issue by v3rmin** [vouill/vue-slideout#14]
**Version:** 1.7.0

```shell
> vue init nuxt-community/starter-template nuxt-sidebar
> cd nuxt-sidebar/
> npm install
> npm install --save vue-slideout
```

```javascript
// layouts/default.vue
<script>
import Slideout from 'vue-slideout'
export default {
  components: {
    Slideout
  }
}  
</script>
```

```shell
> npm run dev
```

**Error:** `Cannot read property 'middleware' of undefined`
**Traceback:**
```javascript
  // nuxt/server.js
  midd = []
  if (layout.middleware) midd = midd.concat(layout.middleware)
  Components.forEach((Component) => {
    if (Component.options.middleware) {
      midd = midd.concat(Component.options.middleware)
```

Why is `options` undefined? Shouldn't all Vue components respond to options? Is this a problem with [nuxt.js](https://github.com/nuxt/nuxt.js) or this plugin?

**Comment by vouill** [comment]
Hello !

So, the first thing to know is that i have never used nuxt, so any kind of help would be apreciated :)

I will check it out a bit further tonight if i can !

Thanks for the issue report !

**Comment by geoandrew** [comment]
Hi Folks;

I just ran into the same problem. It's to do with Server Side Rendering. Please see https://nuxtjs.org/guide/plugins and the section on Client Side Rendering.

I created a plugin file and added slideout. In the plugin def, make sure 'ssr: false'
Then, remove the explicit import and component definition in your page file.

Hope this helps someone!

**Comment by vouill** [comment]
Looks like a good solution ! Thanks for helping @geoandrew . 

Closing this issue then, anyone can feel free to reopen if needed :).

**Comment by popstas** [comment]
plugins/vue-slideout.js:
``` js
import Vue from 'vue';
import Slideout from 'vue-slideout';
Vue.component('Slideout', Slideout);
```

nuxt.config.js:
``` js
  plugins: [
    { src: '~/plugins/vue-slideout', ssr: false }
  ],
```

**Comment by popstas** [comment]
I'm using slideout with nuxt (see config in previous comment) and got error:

```
The client-side rendered virtual DOM tree is not matching server-rendered content
```

See https://github.com/nuxt/nuxt.js/issues/1700, you can avoid this error with wrapping `<Slideout>` to `<no-ssr>` tag
