### ISSUE TITLE
Setting touch prop/option to false doesn't seem to work

### ISSUE THREAD

**Issue by mar7181** [vouill/vue-slideout#15]
Setting touch prop/option to false doesn't seem to work

I set touch=false (or touch="false") and touch is still enabled

`<template>
    <Slideout menu="#slideoutmenu" panel="#wrapper" touch=false :toggleSelectors="['.menu-trigger']" @on-beforeopen="open" @on-beforeclose="close"></Slideout>
</template>`

What I do to fix this issue is this.$children[0].slideout.disableTouch() when the instance is mounted but I'd like to avoid that.

Is this a bug, or is there another/better way to disable touch?

Please note, the only "touch" I want to disable is the touch events that open/close the menu. The other touch events like scroll (scrolling the menu) I want to keep them.

Thanks

**Comment by vouill** [comment]
Hey !

You need to bind the boolean :)

try this :
`:touch="false"`

Keep me updated !

**Comment by mar7181** [comment]
It works perfectly. Thanks and sorry for the invalid issue!
