### ISSUE TITLE
Feature Request - Make padding dynamic

### ISSUE THREAD

**Issue by mberneis** [vouill/vue-slideout#18]
As I calculate the padding attribute depending on the window width I would appreciate if it could be dynamic.
Maybe the attribute could be watched and adjusted when changed without having to refresh the page?

**Comment by vouill** [comment]
Hey!

Not so sure what you want to solve, could you have a repo on codesandbox on what you are doing right now that you want to change ?

**Comment by vouill** [comment]
No updates, closing it
