### ISSUE TITLE
Always on 

### ISSUE THREAD

**Issue by bubnenkoff** [vouill/vue-slideout#2]
Hi! I can't find place where I can set that menu was always shown. Could you help me?

I think it should be near ` :toggleSelectors="['.toggle-button']" @on-open="open"` but I can't figure out what I should to do? Find and modify class `toggle-button` ?

I want to make it's active only on desktop by default and hidden on mobile devices. Is it's possible to do with css?

**Comment by vouill** [comment]
[try this](https://github.com/Mango/slideout/issues/77)

**Comment by bubnenkoff** [comment]
Thanks! I tried, but something seems wrong (do not work for me).

I tried several variants and it's look like I should do something like this:

```
/* Desktop */    
@media only screen and (min-width: 768px) {    
    .slideout-menu {
        position: fixed;
        width: 256px;
        height: 100vh;
        -webkit-overflow-scrolling: touch;
        z-index: 0;
        display: none;
        background-color: #1D1F20;
        color: white;
    }
    .toggle-button 
    {
        display: none;
    }

    .slideout-panel { // <-- add this
    margin-left: 256px;
  }
    
}
```

But after adding it I am getting only white space on left side. I also tried to move here `slideout-panel` but don't get any result...

**Comment by bubnenkoff** [comment]
I got it work!!!

**Comment by bubnenkoff** [comment]
Just:
```
  .slideout-panel {
    margin-left: 256px;
  }

  .slideout-menu {
    display: block;
  }

```

**Comment by vouill** [comment]
👍

**Comment by bubnenkoff** [comment]
@vouill It's seems that it's do not work on mobile browsers :( 
http://shm.code123.org

**Comment by bubnenkoff** [comment]
And it can't be toggled :(

**Comment by vouill** [comment]
It does, your website doesnt use viewport :), add this to your`<head></head>`  in `index.html`

```html
<meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">
```

**Comment by bubnenkoff** [comment]
Thaaanks!!!

**Comment by vouill** [comment]
To toggle it, add a button with any class name you want 
in the example in the repo
```html
<button class="toggle-button">☰</button>
```

is registered as a triggering button by this : 
```html
<Slideout :toggleSelectors="['.toggle-button']"> </Slideout>
```

it can also be an id, `#id`
